### ISSUE TITLE
push hardcoded information to configs

### ISSUE THREAD

**Issue by HarryRybacki-zz** [kmjungersen/znc_admin#11]
Remove hard coded things like IPs from HTML files like [home](https://github.com/kmjungersen/znc_admin/blob/master/templates/home.html#L11) and [register](https://github.com/kmjungersen/znc_admin/blob/master/templates/register.html#L32)

**Comment by asmacdo** [comment]
I agreed. Can you do this @XTech2K

**Comment by kmjungersen** [comment]
Agree.

**Comment by asmacdo** [comment]
Fixed with https://github.com/kmjungersen/znc_admin/pull/14

**Comment by asmacdo** [comment]
register.js Sock object server should be in config file. Currently this needs to be on the server:
    var Sock = new SockJS(SERVER);
And localhost:
    var Sock = new SockJS(LOCALHOST);

This has the unintended effect of breaking the server when it is merged (after it works locally of course). @Xtech2K

**Comment by kmjungersen** [comment]
This has actually been finished for some time in dev, but just now for master.  All config settings are set in `znc_settings.conf`
