### ISSUE TITLE
Ability to change any user's password

### ISSUE THREAD

**Issue by XTech2K** [kmjungersen/znc_admin#20]
At the moment, anybody can change anyone else's password on their znc account simply by creating another user in the registration with the same username and a different password. Doing this gives the username taken error as it should and doesn't create a new user, but changes the user's password to whatever was set as the password of the new account.

**Comment by kmjungersen** [comment]
Working on a fix.  The reason why is because after it gets feedback from znc on whether or not the user exists, it still continues with modifying their password as if they were a newly cloned user.

**Comment by kmjungersen** [comment]
Fixed. :octocat:
